### ISSUE TITLE
Completely broken on Android P 

### ISSUE THREAD

**Issue by codingchili** [codingchili/enigmatic-mouse#46]
It's super broken now. 
```
2019-06-16 16:40:52.575 1735-1757/? I/ActivityManager: Displayed com.codingchili.mouse.enigma/.MainActivity: +276ms [aosp]
2019-06-16 16:40:54.210 9133-9133/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.codingchili.mouse.enigma, PID: 9133
    java.lang.IllegalArgumentException: Invalid Region.Op - only INTERSECT and DIFFERENCE are allowed
        at android.graphics.Canvas.checkValidClipOp(Canvas.java:779)
        at android.graphics.Canvas.clipRect(Canvas.java:826)
        at com.google.android.material.shape.MaterialShapeDrawable.prepareCanvasForShadow(MaterialShapeDrawable.java:850)
        at com.google.android.material.shape.MaterialShapeDrawable.draw(MaterialShapeDrawable.java:746)
        at android.view.View.getDrawableRenderNode(View.java:20485)
        at android.view.View.drawBackground(View.java:20421)
        at android.view.View.draw(View.java:20220)
        at android.view.View.updateDisplayListIfDirty(View.java:19104)
        at android.view.View.draw(View.java:19957)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1246)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
        at android.view.View.updateDisplayListIfDirty(View.java:19095)
        at android.view.View.draw(View.java:19957)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
        at android.view.View.updateDisplayListIfDirty(View.java:19095)
        at android.view.View.draw(View.java:19957)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
        at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:2023)
        at android.view.View.updateDisplayListIfDirty(View.java:19095)
        at android.view.View.draw(View.java:19957)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
        at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:2023)
        at android.view.View.draw(View.java:20232)
        at android.view.View.updateDisplayListIfDirty(View.java:19104)
        at android.view.View.draw(View.java:19957)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
        at android.view.View.updateDisplayListIfDirty(View.java:19095)
        at android.view.View.draw(View.java:19957)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
        at android.view.View.updateDisplayListIfDirty(View.java:19095)
        at android.view.View.draw(View.java:19957)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
        at android.view.View.updateDisplayListIfDirty(View.java:19095)
        at android.view.View.draw(View.java:19957)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
        at android.view.View.updateDisplayListIfDirty(View.java:19095)
        at android.view.View.draw(View.java:19957)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
        at android.view.View.draw(View.java:20232)
        at com.android.internal.policy.DecorView.draw(DecorView.java:791)
        at android.view.View.updateDisplayListIfDirty(View.java:19104)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:686)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:692)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:801)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3323)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3120)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2489)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1464)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7220)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1004)
        at android.view.Choreographer.doCallbacks(Choreographer.java:816)
        at android.view.Choreographer.doFrame(Choreographer.java:751)
2019-06-16 16:40:54.211 9133-9133/? E/AndroidRuntime:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:990)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:198)
        at android.app.ActivityThread.main(ActivityThread.java:6732)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by codingchili** [comment]
Updated Android studio, updated Kotlin plugin, updated Gradle. 

- FingerprintManagerCompat is now deprecated.
- Application doesn't install due to version mismatch - requires a wipe of user data. (****)

**Comment by codingchili** [comment]
```
Installation failed with message Failed to commit install session 1344364068 with command cmd package install-commit 1344364068. Error: INSTALL_FAILED_UPDATE_INCOMPATIBLE: Package com.codingchili.mouse.enigma signatures do not match previously installed version; ignoring!.
It is possible that this issue is resolved by uninstalling an existing version of the apk if it is present, and then re-installing.

WARNING: Uninstalling will remove the application data!

Do you want to uninstall the existing application?
```

**Comment by codingchili** [comment]
```
$ adb backup -f enigmatic.ab -apk com.codingchili.mouse.enigma
adb server is out of date.  killing...
* daemon started successfully *
Now unlock your device and confirm the backup operation.

$ adb restore enigmatic.ab
```

did not work, all application data is lost.

**Comment by codingchili** [comment]
Navigation bar menu looks like **** now. two layers with different color that clips over the text.

**Comment by codingchili** [comment]
Somehow the inner container inherited the color from it's parent, the color was a transparent which of course looks horrible.

Appears the issues are fixed now, I just lost all my stored passwords and the backup didn't even work. What is this even, NodeJS???
